spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.121.0.81:3306/guestroom?serverTimezone=GMT&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/xhweb?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: zou
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 80
  tomcat:
    accept-count: 200
    max-threads: 200
logging:
  path: /usr/java/logger